#!/bin/sh -eu

export CUDA_VISIBLE_DEVICES=0

outdir='test'
DS=4
US=4
UST=8
NOISE=0.1

cmd="python3 ./main.py --outdir "$outdir" --dsx "$DS" --dsy "$DS" --dst "$DS" --usx "$US" --usy "$US" --ust "$UST" --sgma "$NOISE""
echo $cmd
eval $cmd

